# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q52bN3HHof6IpSnQ3EvHboxldo7gMTQU
"""

import streamlit as st

ONGKIR_KOREA = 2000      # dalam KRW
TAMBAHAN_TETAP = 5000    # dalam IDR
TAMBAHAN_DIBAGI = 10000  # dalam IDR

st.set_page_config(page_title="Kalkulator Harga Korea", page_icon="🇰🇷")

st.title("🇰🇷 Kalkulator Harga Korea → Harga Bersih (IDR)")
st.write("Masukkan data berikut untuk menghitung harga bersih per produk:")

harga_krw = st.number_input("💰 Harga produk (KRW)", min_value=0.0, step=100.0)
pembeli = st.number_input("👥 Jumlah pembeli", min_value=1, step=1)
rate = st.number_input("💱 Rate KRW → IDR", min_value=0.0, step=0.1)

if st.button("🔎 Hitung Harga Bersih"):
    harga_idr = harga_krw * rate
    ongkir_per_produk = (ONGKIR_KOREA / pembeli) * rate
    tambahan_per_produk = TAMBAHAN_DIBAGI / pembeli
    total = harga_idr + ongkir_per_produk + TAMBAHAN_TETAP + tambahan_per_produk

    st.subheader("📊 Breakdown Perhitungan")
    st.write(f"- Harga produk (IDR): **Rp {harga_idr:,.0f}**")
    st.write(f"- Ongkir per produk (IDR): **Rp {ongkir_per_produk:,.0f}**")
    st.write(f"- Tambahan tetap: **Rp {TAMBAHAN_TETAP:,.0f}**")
    st.write(f"- Tambahan dibagi: **Rp {tambahan_per_produk:,.0f}**")
    st.success(f"✅ Total Harga Bersih per Produk: **Rp {total:,.0f}**")